server:
  port: 9092
eureka:
  client:
    service-url:
      default-zone: http://localhost:8762/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
spring:    
  jpa:
    database: mysql
    show-sql: true 
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver 
    username: root
    password: 1nt3r4xt3l3ph0nyDB
    url: jdbc:mysql://localhost:3306/middlewarfidb?autoReconnect=true&serverTimezone=UTC    
springdoc:
  api-docs:
    path: /alodigamiddleware-openwebapi          