server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mobile-service
          uri: lb://mobile-service
            - Path=/mobile/**
          filters:
            - AuthFilter
        - id: web-service
          uri: lb://web-service
          predicates:
            - Path=/web/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**