server:
  port: 8085
spring:
  cloud:
    config:
      server:
        git:
          default-label: feature/agonzalez
          uri: https://github.com/Alodiga123/AlodigaMiddlewareAPIConfig
          search-paths: config-data

          
  application:
    name: config-service
