server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: feature/ali
          uri: https://github.com/Alodiga123/AlodigaMiddlewareAPIConfig
          search-paths: config-data

          
  application:
    name: config-service
